version: "2"

services:
  mysql:
    image: mysql:latest # 指定 MySQL 版本
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=passwd # root 密码
      - MYSQL_USER=mysql # 普通用户
      - MYSQL_PASSWORD=passwd # 普通用户密码
      - MYSQL_DATABASE=db_mysql # 数据库名
    volumes:
      - ./mysql_data:/var/lib/mysql # 数据持久化
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    restart: always
  backend:
    image: python:3.13
    container_name: backend-server
    working_dir: /app
    command: bash init.sh
    volumes:
      - ./back:/app
    restart: always