services:
  mysql:
    image: mysql:latest
    container_name: mysql-server # 自己更改名字
    environment:
      - MYSQL_ROOT_PASSWORD=passwd-wehotviz
      - MYSQL_DATABASE=wehotviz
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost",  "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: python:latest
    container_name: backend-server # 自己更改名字
    working_dir: /app
    command: bash init.sh
    volumes:
      - ./back:/app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    
  nginx:
    image: nginx:latest
    container_name: nginx-server # 自己更改名字
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    depends_on:
      - backend